GET http://localhost:3000/subscribers

###
GET http://localhost:3000/subscribers/63e46e5b31ae3e9a83b7f544

###
POST http://localhost:3000/subscribers
Content-Type: application/json

{
  "name": "Amazing Person",
  "subscribedToChannel": "Accompany On"
}

###
DELETE http://localhost:3000/subscribers/63e46a7f93d9612cf2692e4a